### ISSUE TITLE
Oxford Dictionaries v2

### ISSUE THREAD

**Issue by iamsenthilprabu** [MarkFirman/Oxford-Dictionaries-API-Wrapper#1]
Any plan to update this wrapper for Oxford Dictionaries API v2?

**Comment by MarkFirman** [comment]
Working on v2 as I type this - though I will upload it to it's own repository.

**Comment by iamsenthilprabu** [comment]
Cool; Thank you :)

**Comment by MarkFirman** [comment]
It turns out that the V1 API will be deprecated as of June 2019 - therefore I decided to upload V2 directly over this wrapper, as V1 will be useless soon anyway.
